- name: Installa pacchetti
  hosts: all
  become: true # per eseguire il tutto come root
  vars:
    pacchetti:
      - name: docker.io
        state: present
      - name: vim
        state: present
      - name: git
        state: present

  tasks:
    - name: Installo i pacchetti
      package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ pacchetti }}"
