- name: Install Python and Docker
  hosts: all
  become: true
  gather_facts: no
    
  tasks:   
    - name: Install necessary packages
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - python3   
        - python3-pip 
        - docker.io
        - ca-certificates
    
    - name: Install Python dependencies
      pip:
        name: requests
        state: present

    - name: Install Docker GPG APT key
      apt_key:
        url: https://get.docker.com/gpg
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install NTP
      apt:
        name: ntp
        state: present

    - name: time alignment
      timezone:
        name: Europe/Rome

    - name: Pull Docker image
      community.docker.docker_image:
        name: ealen/echo-server
        source: pull

    - name: Crea prova1
      docker_container:
        name: Container1
        image: ealen/echo-server
        state: started

- hosts: nodo1
  become: yes
  tasks:
    - name: start container nodo1
      cron:
        name: nodo1.accensione
        minute: 1-59/2
        job: sudo -i docker start Container1

    - name: stop container nodo1
      cron:
        name: nodo1.spegnimento
        minute: 0-58/2
        job: sudo -i docker kill Container1

- hosts: nodo2
  become: yes
  tasks:
    - name: start container nodo2
      cron:
        name: nodo2.accensione
        minute: 0-58/2
        job: sudo -i docker start Container1

    - name: stop container nodo2
      cron:
        name: nodo2.spegnimento
        minute: 1-59/2
        job: sudo -i docker kill Container1
